import { getEnvSafely } from './config'

const VERCEL_ENVIRONMENT = getEnvSafely(process.env.NEXT_PUBLIC_VERCEL_ENVIRONMENT, 'NEXT_PUBLIC_VERCEL_ENVIRONMENT')
const API_URL = getEnvSafely(process.env.NEXT_PUBLIC_API_URL, 'NEXT_PUBLIC_API_URL')
const SENTRY_DSN = getEnvSafely(process.env.NEXT_PUBLIC_SENTRY_DSN, 'NEXT_PUBLIC_SENTRY_DSN')
const DEFAULT_WALLET_BALANCE = getEnvSafely(process.env.NEXT_PUBLIC_DEFAULT_WALLET_BALANCE, 'NEXT_PUBLIC_DEFAULT_WALLET_BALANCE')
const RPC_URL = getEnvSafely(process.env.NEXT_PUBLIC_RPC, 'NEXT_PUBLIC_RPC')
const TEST_RPC_URL = getEnvSafely(process.env.NEXT_PUBLIC_TEST_RPC, 'NEXT_PUBLIC_TEST_RPC')
const IS_MAINNET = getEnvSafely(process.env.NEXT_PUBLIC_IS_MAINNET, 'NEXT_PUBLIC_IS_MAINNET')

const env = {
  VERCEL_ENVIRONMENT,
  API_URL,
  SENTRY_DSN,
  DEFAULT_WALLET_BALANCE,
  RPC_URL,
  TEST_RPC_URL,
  IS_MAINNET
}

export default env
